pipeline {
    agent any
    
    // Agar aapne Tarika 1 (Jenkins Tools) use kiya hai toh ye rehne dein
    tools {
        nodejs 'node20' 
    }

    stages {
        stage('Environment') {
            steps {
                sh 'node --version'
                sh 'npm --version'
            }
        }

        stage('Install Dependencies') {
            steps {
                // Jenkins ko sahi folder ke andar bhej rahe hain
                dir('react-ci-unit-testing-poc/react-ci-unit-testing-poc') {
                    sh 'npm install'
                }
            }
        }

        stage('Lint') {
            steps {
                dir('react-ci-unit-testing-poc/react-ci-unit-testing-poc') {
                    sh 'npm run lint --if-present'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('react-ci-unit-testing-poc/react-ci-unit-testing-poc') {
                    // Agar tests fail hone par bhi pipeline pass karni ho toh catchError use kar sakte hain
                    sh 'npm test'
                }
            }
        }

        stage('Build') {
            steps {
                dir('react-ci-unit-testing-poc/react-ci-unit-testing-poc') {
                    sh 'npm run build'
                }
            }
        }
    }
}
